# Generated by Django 3.2.7 on 2021-09-26 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_photo_artpost_art'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artpost',
            name='art',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
