# Generated by Django 3.2.7 on 2021-10-02 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_artpost_art'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artpost',
            name='art',
        ),
        migrations.CreateModel(
            name='Art',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('art', models.ImageField(upload_to='images/')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.artpost')),
            ],
        ),
    ]
