# Generated by Django 3.2.7 on 2021-10-03 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20211002_1600'),
    ]

    operations = [
        migrations.AddField(
            model_name='artpost',
            name='hidden',
            field=models.BooleanField(default=True),
        ),
    ]
