# Generated by Django 3.2.7 on 2021-10-19 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0003_auto_20211015_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='friends',
            field=models.ManyToManyField(related_name='_register_userprofile_friends_+', to='register.UserProfile'),
        ),
    ]
