# Generated by Django 3.2.7 on 2021-10-19 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0004_alter_userprofile_friends'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='friends',
            field=models.ManyToManyField(null=True, related_name='_register_userprofile_friends_+', to='register.UserProfile'),
        ),
    ]
